{
  'type': 'module',
  'singleQuote': true,
  'trailingComma': 'all',
  'scripts':
    {
      'test': 'npx -n --experimental-vm-modules -n --no-warnings jest --colors',
    },
  'dependencies': { '@hexlet/immutable-fs-trees': '*', 'lodash': '*' },
  'jest': { 'testEnvironment': 'node' },
}
